# Generated by Django 6.0 on 2025-12-26 19:36

import app.bi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi', '0002_enable_timescaledb_and_hypertable'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='iotmeasurement',
            new_name='bi_iotmeasu_organiz_041ffb_idx',
            old_name='bi_iot_idx',
        ),
        migrations.AlterField(
            model_name='iotmeasurement',
            name='id',
            field=models.UUIDField(default=app.bi.models.uuid7_like, editable=False, primary_key=True, serialize=False),
        ),
    ]
